name: Find Working Directory Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify your desired Python version

      - name: Find Working Directory
        run: |
          echo "Current working directory is: $(pwd)"
